import type { Metadata } from "next";
import "./globals.css";
import { geistSans, spaceGrotesk } from "../utils/fonts";

export const metadata: Metadata = {
  title: "Imprefond",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spaceGrotesk.variable}>
      <body
        className={`${geistSans.variable} ${spaceGrotesk.variable} font-space-grotesk! tracking-tighter antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
